const MAIN_RADIUS = 20;
const LINK_RADIUS = 4;
const LINK_DISTANCE = 16;
const HEADER_SIZE = 67;
const SIDEBAR_WIDTH = 240;

export {MAIN_RADIUS, LINK_DISTANCE, LINK_RADIUS, HEADER_SIZE, SIDEBAR_WIDTH}