// flow constants
const MAIN_RADIUS = 20;
const LINK_RADIUS = 4;
const LINK_DISTANCE = 16;
const HEADER_SIZE = 67;
const SIDEBAR_WIDTH = 240;

// form constants
const DISTANCE_BETWEEN_ELEMENTS = 10;
const DRAWING_PADDING = 150;
const SECTION_PADDING = 50;
const HOVER_COLOR = '#cccccc88';
const SECTION_DEFAULT_HEIGHT = 233;

export {
	MAIN_RADIUS,
	LINK_DISTANCE,
	LINK_RADIUS,
	HEADER_SIZE,
	SIDEBAR_WIDTH,
	DISTANCE_BETWEEN_ELEMENTS,
	DRAWING_PADDING,
	SECTION_PADDING,
	HOVER_COLOR,
	SECTION_DEFAULT_HEIGHT
}